
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.Clear(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.Initialize(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.Remove(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.RemoveGroup(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.SetNextGroup(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.SetNextTag(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.SetOnActivatedCallback(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.SetOnCompleteCallback(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.ShowToastJson(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:MircSharp.ToastNotifications.mToast.ShowToastXml(System.IntPtr,System.IntPtr,System.IntPtr,System.IntPtr,System.Boolean,System.Boolean)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:MircSharp.ToastNotifications.mToast.mIRC")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:MircSharp.cMethod")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:MircSharp.mIRC")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "type", Target = "~T:MircSharp.ToastNotifications.mToast")]